const esModules = [
  'bail',
  'character-entities',
  'color-name',
  'comma-separated-tokens',
  'decode-named-character-reference',
  'devlop',
  'hast-util-from-html',
  'hast-util-from-parse5',
  'hast-util-parse-selector',
  'hastscript',
  'is-plain-obj',
  'micromark',
  'micromark-factory-space',
  'micromark-util-character',
  'micromark-util-combine-extensions',
  'nanoid',
  'parse-entities',
  'property-information',
  'space-separated-tokens',
  'unified',
  'unist-util-is',
  'unist-util-stringify-position',
  'unist-util-visit',
  'vfile',
  'web-namespaces',
]

module.exports = {
  clearMocks: true,
  preset: 'ts-jest/presets/js-with-babel',
  prettierPath: null,
  setupFiles: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'node',
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  transformIgnorePatterns: [`/node_modules/(?!${esModules.join('|')})`],
}
